FROM odoo:18.0

USER root

# KHÔNG upgrade pip nữa
# Cài luôn dependencies
RUN pip3 install --no-cache-dir --break-system-packages \
    python-dotenv \
    google-auth \
    google-auth-oauthlib \
    google-auth-httplib2 \
    requests

USER odoo